#!/bin/bash

cp /System/Library/Frameworks/Tcl.framework/Versions/8.5/Tcl ./dist/GasChromino
cp /System/Library/Frameworks/Tcl.framework/Versions/8.5/Tcl ./dist/GasChromino.app/Contents/MacOS
cp /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk ./dist/GasChromino
cp /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk ./dist/GasChromino.app/Contents/MacOS